name: CI
on:
  push:
    branches:
      - main

jobs:
  flutter_apkbuild:
    name: Run flutter test and build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v1
        with:
          name: android
          path: build/app/outputs/apk/release/app-release.apk
